/*
 * This source file was generated by the Gradle 'init' task
 */
package opp.project.t4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class KanbanAppTest {
    /*
     * Implement a custom data structure that can hold, add, remove, and update cards across the board.
     */
    
}
