import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, SignInButton } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "The Kanban App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div>{children}</div>
          <div className="fixed bottom-4 right-4">
            <SignInButton>
              <button className="bg-blue-500 text-white px-4 py-2 rounded">
                Sign In
              </button>
            </SignInButton>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
