// /src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import  ClientWrapper  from "./components/ClerkAuthenticator/ClientWrapper/ClientWrapper"; // Adjust the path as needed
import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "The Kanban App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={`${geistSans.variable} bg-gray-50`}>
        <SignedIn>{children}</SignedIn>
        <SignedOut>
          <RedirectToSignIn signInFallbackRedirectUrl={"pages/sign-in"}/>
        </SignedOut>
      </body>
    </html>
    </ClerkProvider>
  );
}