/*
 * This source file was generated by the Gradle 'init' task
 */
package opp.project.t4;

public class Task {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Task().getGreeting());
    }
}
